version: '3'

networks:

  default:

services:
  php:
    build:
      context: ../
      dockerfile: ./docker/php/Dockerfile
    container_name: php
    networks:
      - default
    ports:
      - '8384:80'
    restart: unless-stopped
    volumes:
      - ../server/:/var/www/html/

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysql
    environment:
      MYSQL_DATABASE: challenge_sales
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - mydb:/var/lib/mysql

  node:
    image: node:18
    restart: always
    container_name: nodejs
    command: "npm run dev"
    user: "node"
    working_dir: /home/node/app
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - ../client/:/home/node/app

volumes:
  mydb: